### ISSUE TITLE
Front-End: HTML Mock-ups

### ISSUE THREAD

**Issue by zachmay** [zachmay/inventory616#7]
Mock up all screens in HTML 5/CSS using Bootstrap.

The goal here is to get all of the wireframe mockups from the Phase I document turned into HTML we can use later, even if they're currently not wired up to anything.

Certainly discuss with @sjcurt02 about tweaks, changes, etc.

**Comment by ybwirian** [comment]
Please check all updated pages:
http://www.cs.uky.edu/~ywi224/CS616/index.html
http://www.cs.uky.edu/~ywi224/CS616/building.html
http://www.cs.uky.edu/~ywi224/CS616/room.html
http://www.cs.uky.edu/~ywi224/CS616/checkin.html
http://www.cs.uky.edu/~ywi224/CS616/scan.html
http://www.cs.uky.edu/~ywi224/CS616/finditem.html
http://www.cs.uky.edu/~ywi224/CS616/item.html

Based on our last team discussion, we decided to remove the side menu since it will confuse the users.

The one thing left is “report” menu which I believe I can finish it today.

However I need (badly) a second eye to check it. I will try to update the pages based on Zack’s feedback later on.

**Comment by ybwirian** [comment]
Kindly check the final new pages:
http://www.cs.uky.edu/~ywi224/CS616/report_itemhistory.html
http://www.cs.uky.edu/~ywi224/CS616/report_viewhistory.html
http://www.cs.uky.edu/~ywi224/CS616/report_itemhistorybytype.html
http://www.cs.uky.edu/~ywi224/CS616/report_itemreconciliation.html

**Comment by ForeverTangent** [comment]
The New Pages should be Sumbitted.  I sent a pull request  but it says it is merged.
